### ISSUE TITLE
Proposal of list enhancements

### ISSUE THREAD

**Issue by nbonbon** [stevematthew/awesome-climate-change#9]
- Add descriptors to sections to help people place links in correct location
- Order links in each section alpabetically

**Comment by stevematthew** [comment]
I really like these suggestions.

I'm travelling until early Jan and will take a look then.

**Comment by stevematthew** [comment]
Sorted the links within each section: https://github.com/stevematthew/awesome-climate-change/commit/559148ff0610d555d900b3c25be89418b72dfed7

Added section descriptions: https://github.com/stevematthew/awesome-climate-change/commit/1a8e8d9a457db15e30081d5ab8fae2bf9495892b
